name: weather
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  test: ^1.15.7
  http: ^0.12.2
  line_icons: ^1.3.2
  flutter_weather_icons: ^1.0.2
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.3
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  connectivity: ^3.0.3
  flutter_launcher_icons: ^0.9.0
  flutter_svg: ^0.22.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/icon.png"
  adaptive_icon_foreground: "assets/launcher/icon.png"

flutter:

  uses-material-design: true
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/fonts/MyFlutterApp.ttf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

  assets:
    - lang/en.json
    - lang/fa.json
    - assets/database/cities.sqlite
    - assets/images/No Internet Connection UI.jpg
    - assets/images/background-light.svg