name: weather
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  test: ^1.15.7
  http: ^0.12.2
  line_icons: ^1.3.2
  fl_chart: ^0.12.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Shabnam
      fonts:
        - asset: fonts/Shabnam.ttf

  assets:
    - lang/en.json
    - lang/fa.json